name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Fetch events
        run: |-
          sudo timedatectl set-timezone Asia/Shanghai
          yarn
          yarn start

      - name: Commit and push
        run: |-
          git config --global user.email "bot@github.com" && git config --global user.name "Bot"
          git add . && git commit -m ":memo: Update Data" || exit 0
          git push
